spring.application.name=Config-Server-Condominio
server.port = 8887
spring.cloud.config.server.git.uri=https://github.com/marcoc1976/Condominio-Config.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=.
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.username=marcoc1976
spring.cloud.config.server.git.password= ${GIT_TOKEN}
#Configurazione RabbitMq per i aggiornare con un'unica post su bus tutti i properties dei microservizi
spring.rabbitmq.host=http://192.168.1.251
spring.rabbitmq.port=5672
spring.rabbitmq.username=mario
spring.rabbitmq.password=superpassword
spring.rabbitmq.virtual-host=condominio


