spring.cloud.config.server.git.uri=https://github.com/marcoc1976/Condominio-Config.git
spring.cloud.config.server.git.default-label=spesecondominiali
spring.cloud.config.server.git.search-paths=.
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.username=marcoc1976
spring.cloud.config.server.git.password=${GIT_TOKEN}
#Configurazione RabbitMq per i aggiornare con un'unica post su bus tutti i properties dei microservizi
spring.rabbitmq.host=192.168.1.251
spring.rabbitmq.port=5672
spring.rabbitmq.username=mario
spring.rabbitmq.password=${PWD_RABBITMQ}
spring.rabbitmq.virtual-host=condominio
#abilitazione del busrefresh per rabbitMq
#con * tutti gli end point, meglio in produzione esporre solo l'end point necessario per rabbitmq
management.endpoints.web.exposure.include=*
management.endpoint.busrefresh.access=unrestricted
management.endpoint.refresh.enabled=true